server:
  port: 9001
  servlet:
    context-path: /imooc

spring:
  application:
    name: e-commerce-gateway
  cloud:
    nacos:
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: public
#    gateway:
#      routes:
#        - id: e-commerce-authority-center
#          uri: http://127.0.0.1:7000
#          predicates:
#            - Path=/ecommerce-authority/authority/**
#        metadata:
#          management:
#            context-path: ${server.servlet.context-path}/actuator

#读取指定文件下配置
nacos:
  gateway:
    route:
      config:
        data-id: e-commerce-gateway-router
        group: e-commerce

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
