server:
  port: 1001
  servlet:
    context-path: /e-commerce-admin

spring:
  application:
    name: e-commerce-admin
  cloud:
    nacos:
      discovery:
        enabled: true
        #ncaos client 端口地址
        server-addr: 127.0.0.1:8848
  #        namespace: fe40f889-aa06-40e1-9051-36c20bd8d6f8


  thymeleaf:
    check-template: false
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: '*' #需要开放的端点。默认值只打开health 和info两端点。通过设置 * 可以开放所有端点
  endpoint:
    health:
      show-details: always